version: '3.9'

services:
  apache:
    image: "httpd:latest"
    volumes:
      - /var/containers/sites/test/apache/rw/html:/var/www/html
      - /var/containers/sites/test/apache/ro/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - /var/containers/sites/test/apache/ro/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - /var/containers/sites/test/apache/ro/httpd-mpm.conf:/usr/local/apache2/conf/extra/httpd-mpm.conf
    networks:
      - testsite_internal
      - traefik-public
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.apache-http.rule=Host(`markerstage-testsite.cratis.cc`)
        - traefik.http.routers.apache-http.entrypoints=http
        - traefik.http.routers.apache-http.middlewares=https-redirect
        - traefik.http.routers.apache-https.rule=Host(`markerstage-testsite.cratis.cc`)
        - traefik.http.routers.apache-https.entrypoints=https
        - traefik.http.routers.apache-https.tls=true
        - traefik.http.services.apache.loadbalancer.server.port=80

  phpfpm:
    image: "hutinskit/phpfpm:v1.0.30"
    volumes:
      -  /var/containers/sites/test/apache/rw/html:/var/www/html
      -  /var/containers/sites/test/php/ro/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - testsite_internal
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker

  memcached:
    image: "memcached:latest"
    networks:
      - testsite_internal
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker

networks:
  testsite_internal:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
