FROM php:8.2.7-fpm-alpine

RUN apk update && apk add --no-cache \
    zlib-dev \
    libmemcached-dev \
    openssl-dev \
    imagemagick-dev \
    icu-dev \
    libmcrypt-dev \
    libzip-dev \
    libpng-dev \
    libedit-dev \
    libxml2-dev \
    libxslt-dev \
    bzip2-dev \
    oniguruma-dev \
    curl-dev \
    autoconf \
    make \
    g++ \
    && rm -rf /var/cache/apk/*

RUN pecl install imagick msgpack igbinary memcached \
    && docker-php-ext-enable imagick msgpack igbinary memcached \
    && docker-php-ext-install pdo_mysql mysqli bcmath intl mbstring opcache soap xsl zip gd bz2 curl

CMD ["php-fpm"]

